// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

const SUPABASE_URL = "https://djbhknvjpecdztjibewo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqYmhrbnZqcGVjZHp0amliZXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjI0NTgsImV4cCI6MjA2NTczODQ1OH0.AlEa90vo_l1fvloX7v8Hec_ABSHXczoJHKaxR3Et5_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storage: {
      getItem: (key: string) => {
        return sessionStorage.getItem(key);
      },
      setItem: (key: string, value: string) => {
        sessionStorage.setItem(key, value);
      },
      removeItem: (key: string) => {
        sessionStorage.removeItem(key);
      }
    },
    detectSessionInUrl: true,
    flowType: 'implicit'
  }
});